Method DR.SC
SpatialHackathon/SpaceHack2023 pull request #122
Opened 2023-12-13 15:26 UTC by shdam

DR.SC implemented (Issue #21)

Package is on CRAN, but not available for R 4.3.2, which is the version where SpatialExperiment. Therefore, I had to get it from GitHub.
The environment can be created with drsc_env.sh.

It was not possible to use the neighbors for this, as their neighbor function is hardcoded to be run. 
Seurat needs a counts and logcounts assay, so I just added the counts matrix as both.

2023-12-13 15:40 UTC, niklasmueboe requested changes

2023-12-14 13:04 UTC, shdam commented on method/DRSC/DRSC.r
> +seurat_obj <- FindSVGs(seurat_obj, verbose=FALSE)
I now assign the features as `seurat_obj[["originalexp"]]@var.features <- rownames(rowData(spe))`, as they are subset to the selected when generating spe:
`spe <- spe[as.logical(rowData(spe)$selected), ]`

How would I add the normalized data? Is that a separate file input?

2023-12-14 13:10 UTC, niklasmueboe commented on method/DRSC/DRSC.r
> +seurat_obj <- FindSVGs(seurat_obj, verbose=FALSE)
Assume that the matrix_file is preprocessed as needed

2023-12-14 13:58 UTC, shdam commented
All comments addressed :)

2023-12-14 13:59 UTC, shdam commented on method/DRSC/DRSC.yml
I removed spatialexperiment as a dependency and got it to work with the CRAN version of the package.

2023-12-14 13:59 UTC, shdam commented on method/DRSC/DRSC.r
> +seurat_obj <- FindSVGs(seurat_obj, verbose=FALSE)
Got it. Wrote it as "normalized counts" in the sheet.

2023-12-14 14:09 UTC, niklasmueboe requested changes

2023-12-14 14:34 UTC, niklasmueboe approved these changes

2023-12-14 14:34 UTC, niklasmueboe commented on method/DRSC/DRSC.r
> +    assay(spe, "logcounts", withDimnames = FALSE) <- log1p(as(Matrix::t(Matrix::readMM(matrix_file)), "CsparseMatrix"))
Which of the assays will be used. Log counts? or counts?

2023-12-14 14:53 UTC, shdam commented on method/DRSC/DRSC.r
> +    assay(spe, "logcounts", withDimnames = FALSE) <- log1p(as(Matrix::t(Matrix::readMM(matrix_file)), "CsparseMatrix"))
Good point! I am not a big Seurat user - but I checked and it is the logcounts slot that is used. It gets renamed to "data" when running as.seurat, and the package uses the "data" slot. So it did make a difference!

2023-12-14 14:58 UTC, merged