Method conST
SpatialHackathon/SpaceHack2023 pull request #223
Opened 2024-02-22 15:17 UTC by heylf

This tackles the issue #20 to add conST as a method.

I contacted the authors and they have added MIT license. 

Please check the two TODOs. The method has generally standard processing. GPU is not necessarily required but recommended.

2024-02-26 10:38 UTC, niklasmueboe requested changes

2024-02-26 10:38 UTC, niklasmueboe commented on method/conST/conST.py
> +def adata_preprocess(i_adata, min_cells=3, pca_n_comps=300):
If they run this with 300 PCs we should probably keep this separate from the preprocessing, I don' think we will scale the numbers of PCs that high. Also I am sceptical about how much information these PCs are adding.

2024-02-26 10:38 UTC, niklasmueboe commented on method/conST/config/config_1.json
Can we reduce the number of parameters to the ones we are likely to actually change? I think for most of the other methods we stuck to keeping the architectural parameters at theri defaults.

2024-02-26 10:38 UTC, niklasmueboe commented on method/conST/config/config_1.json
> +    "shape": "hexagon"
The shape should probably be detected from the technology.

2024-03-04 12:54 UTC, heylf commented
@niklasmueboe finished your review

2024-03-15 08:14 UTC, niklasmueboe approved these changes

2024-03-15 08:14 UTC, merged