Added MVP for SpiceMix.
SpatialHackathon/SpaceHack2023 pull request #91
Opened 2023-12-12 02:56 UTC by alam-shahul

Following the SpaGCN example, I created a script/Conda YAML for SpiceMix.

Note: I am one of the coauthors of SpiceMix. I used my own implementation of SpiceMix, as opposed to the code that was originally used in the SpiceMix paper. This is because I am currently working on an extension to SpiceMix, and the code that I have implemented for this extension is a more user-friendly and efficient version. There are some slight differences in comparison to how the original SpiceMix code/algorithm works, but the core of the algorithm is the same.

2023-12-14 08:33 UTC, niklasmueboe requested changes

2024-01-26 10:18 UTC, alam-shahul commented
It should be as simple as changing `cuda:0` to `cpu` in the config files under the `device` field. But I think it would be a lot slower than with the GPU.

2024-01-26 10:47 UTC, shdam commented
> It should be as simple as changing `cuda:0` to `cpu` in the config files under the `device` field. But I think it would be a lot slower than with the GPU.

Niklas reminded me that I was running on a CPU node, why GPU of course didn't work. So the error was a non-issue.
Unless he is happy as is, I will double check it still runs smoothly on a GPU node when my other session has finished running.

2024-01-29 07:31 UTC, shdam approved these changes

2024-01-29 07:35 UTC, shdam commented on method/SpiceMix/SpiceMix.py
How can I label this as complete?

2024-01-29 07:36 UTC, shdam approved these changes

2024-01-29 07:54 UTC, shdam approved these changes

2024-01-29 13:23 UTC, niklasmueboe approved these changes

2024-01-29 13:23 UTC, merged