SEA_AD data uploader
SpatialHackathon/SpaceHack2023 pull request #92
Opened 2023-12-12 08:14 UTC by berl

2023-12-13 09:08 UTC, niklasmueboe requested changes

2023-12-14 09:54 UTC, niklasmueboe approved these changes

2023-12-14 09:55 UTC, merged

2024-01-22 14:48 UTC, markrobinsonuzh commented
@berl Would you be able to add info about this `SEA_AD` dataset in the [Google Sheet](https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=1453488771) ? Unless I'm mistaken, it is not currently there.

2024-01-23 19:27 UTC, berl commented
@markrobinsonuzh  done!